### ISSUE TITLE
How can I input audio?

### ISSUE THREAD

**Issue by tdh8316** [mohammad1ta/arduino-equalizer#1]
Hi, I'm planning to make an audio spectrum analyzer and found this.
But I have no clue how I can input audio.
`Connect R line of your audio input to analog pin ( A0 ) and Ground line to ground of the board.`
I couldn't understand how to achieve. Entirely my bad 😭 

Can you provide a wiring diagram or an image of your implementation?

And I wonder what module is required to read audio signal.

Thanks!

**Comment by mohammad1ta** [comment]
Dear @tdh8316 ,

Unfortunately, I'm not at home now to help you better. But I found a picture from my gallery, and it shows my board. ( I've attached in below )

You don't need any extra module to read audio signal, Analog0 ( A0 ), can read your sound.

If you know, audio cable has 2 or 3 wire. ( one left, one right, one ground )... and you must connect **R wire** to the A0 as input.

![IMG_0380](https://user-images.githubusercontent.com/6240044/77472625-82bc4800-6e14-11ea-9d85-ca04682fbc39.jpg)

If you need more help, please tell me.
Good luck :)

**Comment by tdh8316** [comment]
Thanks for answer! I had to know what module is needed to make an estimate for budget.

Best regards,

**Comment by mohammad1ta** [comment]
You are welcome,

Kind regards
